### ISSUE TITLE
Cannot configure JMX ports in deployment.toml file

### ISSUE THREAD

**Issue by chanikag** [wso2/micro-integrator#1047]
**Description:**
The following cannot be configured.

To configure JMX monitoring ports
[monitoring.jmx]
rmi_hostname = localhost
rmi_registry_port = 9999
rmi_server_port = 11111

Disable JMX monitoring
[monitoring.jmx]
rmi_server_start = true

Enable JMX for datasources
[database.shared_db]
jmx_enable = true

To disable JMX thread view
[jmx_thread_view]
synapse.jmx.thread.view.enabled=false

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by chanikag** [comment]
Once this is fixed https://github.com/wso2/docs-ei/blob/7.0.0/en/micro-integrator/docs/administer-and-observe/jmx_monitoring.md has to be changed with the configs

**Comment by Vathsan** [comment]
JMX remote monitoring feature is not available in Micro Integrator. The reason is to make MI more lightweight.
Our recommendation is to use Prometheus for monitoring. You may refer to https://ei.docs.wso2.com/en/latest/micro-integrator/setup/observability/observability-deployment-strategy/#! on how to setup observability in MI.
