### ISSUE TITLE
Message Processor state is not saved properly in MI registry

### ISSUE THREAD

**Issue by Vathsan** [wso2/micro-integrator#1071]
**Description:**
The Activate parameter we configure in synapse configurations is only helpful for the message processor to deploy for the very first time. Once it is deployed, the message processor's state is preserved in the registry [1]. The current state is assigned to the property MESSAGE_PROCESSOR_STATE and saved in the registry (<MI-HOME>/registry/governance/repository/components/org.apache.synapse.message.processor). 

In MI the state of the message processor is not properly stored as a property. It should be stored as key-value pair as shown below,
`MESSAGE_PROCESSOR_STATE=PAUSED`

but the value is stored without the property name.

**Steps to reproduce:**
1. Configure JMS transport for Active MQ by following the documentation [2]
2. Configure JMS Message Store, Scheduled Message Forwarding processor and the Proxy service by following the doc [3]
3. Invoke the Proxy Service

[1] https://github.com/wso2/wso2-synapse/blob/2a1064286a31d2efa458b31da4d518e1f60b6df1/modules/core/src/main/java/org/apache/synapse/message/processor/impl/ScheduledMessageProcessor.java#L564
[2] https://ei.docs.wso2.com/en/latest/micro-integrator/setup/brokers/configure-with-ActiveMQ/
[3] https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/examples/jms_examples/guaranteed-delivery-with-failover/

**Comment by lkokila** [comment]
The case is when the message processor gets disabled (manually disabling or after getting disabled upon an endpoint failure), even after enabling the message processor through the developer studio when the updated CAR file is executed through the Micro Integrator still the message processor waits in a disabled/paused state with the following log in the micro integrator. 

`{org.wso2.micro.integrator.ntask.core.impl.AbstractQuartzTaskManager} - Task scheduled: [-1234][ESB_TASK][MSMP_TestMessageProcessor0][Paused]`

As a workaround, the related message processor file (_meta_MSMP_<NAME_OF_THE_MESSAGE_PROCESSOR>
) can be updated as follows to change the state. 

`<IntegrationStudio_home>/runtime/microesb/registry/governance/repository/components/org.wso2.carbon.tasks/definitions/-1234/ESB_TASK/`

`TASK_STATE_PROPERTY=NORMAL`

**Comment by Nirothipan** [comment]
We are discussing two different issues here.

**1st Issue** 
Mentioned by @Vathsan  is because the value is not written in the registry properly and the read fails. However this was introduced as a fix for https://github.com/wso2/product-ei/issues/872 and it will be needed when clustered only. Hence this should be an issue in MI 1.1.0.

**2nd Issue** 
Mentioned by @lkokila, under this circumstance we need to manually enable the processor as we do in EI Management console. Here we might use the [Management API](https://ei.docs.wso2.com/en/latest/micro-integrator/administer-and-observe/working-with-management-api/#post-message-processors) for this purpose.
