### ISSUE TITLE
API details are not populated correctly in Dashboard

### ISSUE THREAD

**Issue by Vathsan** [wso2/micro-integrator#1877]
**Description:**
For an API with URL http://localhost:8290/vathsan, the API details page shows the following in Dashboard,
![image](https://user-images.githubusercontent.com/29911181/87757937-29e04780-c829-11ea-98d2-a6c848675459.png)

**Suggested Labels:**
Bug

**Comment by sachithKay** [comment]
These attributes will only be populated in the UI if you define them in the API configurations. Otherwise the default host and port values will be displayed (empty and -1 respectively).
Please find the api attached below which has host name and port defined.

```
<api xmlns="http://ws.apache.org/ns/synapse" name="api" context="/api" hostname="ei.sachith" port="9164" version-type="context">
   <resource methods="POST GET" uri-template="/context1">
      <inSequence>
         <drop/>
      </inSequence>
   </resource>
</api>
```

This API configuration will be displayed in the dashboard as follows.
<img width="1424" alt="Screen Shot 2020-07-31 at 10 20 26 AM" src="https://user-images.githubusercontent.com/22365810/89001488-fcf75e80-d317-11ea-98f1-ccbc65247d35.png">
