### ISSUE TITLE
JMX monitoring is not enabled

### ISSUE THREAD

**Issue by satyasivaprasad1982** [wso2/micro-integrator#1939]
**Description:**
Using MI 1.1.0 (EI 7.0.2) , not getting the JMX monitoring option

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
MI 1.1.0, EI 7.0.2, Integration studio 7.0.2

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
JMX configurations as below present in carbon.xml in <EI_HOME>]7.0.2\micro-integrator\conf.
<JMX>
<RMIRegistryPort>9999</RMIRegistryPort>
<RMIServerPort>11111</RMIServerPort>
</JMX>

Started the MI. It did not print the JMX server URL on the console. 
Opened the Jconsole and manually entered the Remote process as below - 
service:jmx:rmi://localhost:11111/jndi/rmi://localhost:9999/jmxrmi

Entered the credentials as admin, admin. It gave an error - Connection did not succeed. 

Tried to give the below configurations in deployment.toml under <EI_HOME>]7.0.2\micro-integrator\conf
and restarted the MI and tried to connect with Jconsole. Same error again.

[monitoring.jmx]
rmi_hostname = "localhost"
rmi_registry_port = 9999
rmi_server_port = 11111
rmi_server_start = true

Tried both true and false for the parameter above- "rmi_server_start"

**Related Issues:**
#1047

**Comment by Vathsan** [comment]
Hi @satyasivaprasad1982, JMX remote monitoring feature is not available in Micro Integrator. The reason is to make MI more lightweight. 
Our recommendation is to use Prometheus for monitoring. You may refer to https://ei.docs.wso2.com/en/latest/micro-integrator/setup/observability/observability-deployment-strategy/#! on how to setup observability in MI.
