### ISSUE TITLE
[User Mgt] Allows to delete the logged in User itself

### ISSUE THREAD

**Issue by Nirothipan** [wso2/micro-integrator#2241]
**Description:**
Create a user using Dashboard UI.

Login using that user.

Delete the same user.

User gets deleted from the own account and still proceed doing other stuffs with no issuses ( adding new users and etc.)

**Comment by Nirothipan** [comment]
This seems to be be because delete request is send with token of the admin user.

![Screenshot from 2021-04-14 08-39-09](https://user-images.githubusercontent.com/24619763/114648723-ebff4980-9cfc-11eb-9771-6250191a0b38.png)

**Comment by dulanjalidilmi** [comment]
PR https://github.com/wso2/product-mi-tooling/pull/203 disable deleting the logged in user from UI. We use the super admin credentials in order to invoke the management api from dashboard backend, which is configured in the deployment.toml in the dashboard. This will be changed once we implement a dedicated userstore for the dashboard.
