### ISSUE TITLE
Unable to undeploy/redeploy faulty CAR in Centralized ESB with EI 7.1.0

### ISSUE THREAD

**Issue by Thilinika** [wso2/micro-integrator#2282]
**Description:**
Since the hot deployment is available in EI-7.1.0 it is possible to deploy and undeploy car apps without restarting the server. The issue occurs when trying to deploy a faulty car app. As similar in case of EI-6.x car file moves to faulty car. When trying to undeploy the car file can see a message like this:

`INFO {CappDeployer} - Undeploying Faulty Carbon Application On : /home/wso2usr/wso2mi-1.2.0/repository/deployment/server/carbonapps/sample-cap_1.0.0-SNAPSHOT.car `

But it doesn't show anything else and the artifacts remain in the server. So a redeploy fails with the error message (for example for a sequence):

`ERROR {SequenceDeployer} - Sequence named : sample_v1_1_seq already exists.`

The only way to delete or redeploy the CAR is to delete or modify the CAR in the carbonapps folder and restart the server which affects all the other car apps which are already deployed.

**Affected Product Version:**
EI 7.1.0

**Comment by DiegoBetancourtC** [comment]
I'm having the same problem. I took some code from an older proxy service version of the WSO2 EI and re-use it in the WSO2 Micro Integrator 1.2.0, the outcome: A faulty CAR application that the Micro Integrator didn't detect when it was initially deployed (which I think is the culprit behind all of this), only when it is re-deployed.

Workaround (while this issue is fixed):

Recreate the faulty CAR app by creating it from scratch using the Graphical tools of the Integration Studio, then when you have the skeleton of your proxy service, then replace only the attribute values of the old proxy service into the new one. Export your CAR App. Test it by deploying it in your WSO MI version and re-deploying it again to check that you don't receive the `Already Name Service Exists` error.
