### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by a5anka** [wso2/micro-integrator#238]
This is the ZenHub EPIC used to group all REST API related issues.

**Comment by Nirothipan** [comment]
Shall we make the query param to check the existence of the artifact unique.

i.e make everything as just **name** ? Since it should be intuitive form the first path param.

For example in the following

https://localhost:9164/management/applications?carbonAppName          **carbonAppName**

https://localhost:9164/management/apis?apiName                                  **apiName**

https://localhost:9164/management/endpoints?endpointName               **endpointName**

we can simply pass the query param as name like following. Hence it would be more user friendly I suppose.

https://localhost:9164/management/applications?name         

https://localhost:9164/management/apis?name                                

https://localhost:9164/management/endpoints?name          

Changing the syntax might cause backward compatible issues, anyway since we just started I wanted to propose this.


WDYT  @a5anka  @SanojPunchihewa 
cc @sachithKay

**Comment by a5anka** [comment]
:+1: 

I would like to add a small thing. Instead of the name being a query param it is better to be the last element of the resource path.

For example,
https://localhost:9164/management/applications/hello-world-capp

**Comment by Nirothipan** [comment]
> I would like to add a small thing. Instead of the name being a query param it is better to be the last element of the resource path to make it more RESTful.
> 
> For example,
> https://localhost:9164/management/applications/hello-world-capp

+1 if doable. That would be more clear .

However if we are to do this, we need to do a path param mapping after it hits the resource having the resource registered as applications/{name} for eg.

@SanojPunchihewa  or @sachithKay  shall we please see whether which is doable and change the implementation accordingly.

@a5anka  I trust we can change the current implementation , will there be backward compatible issues or etc that affects drastically.

**Comment by a5anka** [comment]
> @a5anka I trust we can change the current implementation , will there be backward compatible issues or etc that affects drastically.

From the user's perspective, they will have to change since we have moved from XML to JSON. (we can provide an MI docker image with integrations required to make it compatible with the old API :smiley:)

**Comment by SanojPunchihewa** [comment]
> @SanojPunchihewa or @sachithKay shall we please see whether which is doable and change the implementation accordingly.

Yes, we can change the implementation and as @Nirothipan mentioned we need to do a path param mapping in our ApiDispatcher and update the CLI to use path params instead query params
