### ISSUE TITLE
Running micro integrator on VM, Docker and K8s 

### ISSUE THREAD

**Issue by kasun04** [wso2/micro-integrator#53]
Create a doc for this and add it to the main readme.

**Comment by a5anka** [comment]
I added documentation related to using micro integrator with VM in https://github.com/wso2/micro-integrator/pull/56 and https://github.com/wso2/micro-integrator/pull/57

**Comment by a5anka** [comment]
Instructions on using micro integrator with docker added in #58

**Comment by a5anka** [comment]
IMO we do not have to do anything additional to install micro integrator in k8s since we can use the docker image with artifacts to deploy micro integrator. Therefore I think we only require a document explaining how we can deploy the docker image in k8s.

**Comment by kasun04** [comment]
No, that's is not enough. We need to give a template K8s descriptor(with ingress, deployment, service etc.) to deploy the Micro integration scenario to the K8s.

**Comment by a5anka** [comment]
I added k8s deploying instructions to the helloworld sample in https://github.com/wso2/micro-integrator/pull/76.

**Comment by a5anka** [comment]
I am closing this issue since we have added the relevant information in https://github.com/a5anka/micro-integrator/blob/master/doc/working-with-the-micro-integrator.md. 

We started on a getting started guide as well https://github.com/wso2/micro-integrator/tree/master/examples/getting-started. We are planning to add observability stuff there as well.
