### ISSUE TITLE
OSGI console does not work with -DosgiConsole parameter

### ISSUE THREAD

**Issue by a5anka** [wso2/micro-integrator#61]

**Comment by Ibaqu** [comment]
-DosgiConsole parameter does not work while executing micro-integrator.sh (found in <M.I Home>/bin ) however it does work with wso2server.sh (found in <M.I Home>/wso2/micro-integrator/bin) 

To solve the current issue: The MicroIntegrator folder structure needs to be changed so as to bring wso2server.sh as the main executable rather than using micro-integrator.sh

**Comment by a5anka** [comment]
@Ibaqu we have changed the folder structure in master now. Can you check whether the issue is resolved now?

**Comment by Ibaqu** [comment]
@a5anka I tested the -DosgiConsole parameter and it works with the current structure

**Comment by malakaganga** [comment]
Related to : https://github.com/wso2/micro-integrator/issues/41
Fixed with : https://github.com/wso2/micro-integrator/pull/68
